--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "DB2INST1"."CUSTOMERS_PRODUCTS" (
		"CUSTOMERID" BIGINT NOT NULL,
		"PRODUCTNAME" VARCHAR(20) NOT NULL,
		"PHONENUMBER" VARCHAR(20),
		"OWNEDPRODUCTS_NAME" VARCHAR(254),
		"CUSTOMER_ID" BIGINT
	)
	DATA CAPTURE NONE;

CREATE INDEX "DB2INST1"."I_CSTMCTS_CUSTOMER"
	ON "DB2INST1"."CUSTOMERS_PRODUCTS"
	("CUSTOMER_ID"		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE INDEX "DB2INST1"."I_CSTMCTS_PRODUCT"
	ON "DB2INST1"."CUSTOMERS_PRODUCTS"
	("OWNEDPRODUCTS_NAME"		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

ALTER TABLE "DB2INST1"."CUSTOMERS_PRODUCTS" ADD CONSTRAINT "SQL180112224205470" PRIMARY KEY
	("CUSTOMERID",
	 "PRODUCTNAME");

