--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "DB2INST1"."PRODUCTS" (
		"NAME" VARCHAR(20) NOT NULL,
		"DOWNLOADSPEED" INTEGER,
		"MONTHLYUSAGE" INTEGER,
		"PACKAGENAME" VARCHAR(50),
		"PRICE" DOUBLE,
		"PRODUCTCATEGORY" VARCHAR(50),
		"CREATIONDATE" TIMESTAMP,
		"UPDATEDATE" TIMESTAMP
	)
	DATA CAPTURE NONE;

ALTER TABLE "DB2INST1"."PRODUCTS" ADD CONSTRAINT "SQL180112042935210" PRIMARY KEY
	("NAME");

