version: '3'
services:
    db2express:
        image: ibmcom/db2express-c
        hostname: db2express
        ports:
            - "50000:50000"
        environment:
            DB2INST1_PASSWORD: db2admin-pwd
            LICENSE: accept
        volumes:
            - ./dbdata:/share
        command: db2start
    web:
        image: ibmcase/greencompute-telco-app
        hostname: webapp
        ports:
            - "3001:3001"
