export class Customer {
  id: number;
  name : string;
  firstName : string;
  lastName: string;
  gender: string;
  emailAddress: string;
  estimatedIncome: number;
  age: number;
  profession: string;
  children: number;
  usage:number;
  maritalStatus:string;
  ratePlan: string;
  carOwner: string;
  type: string;
  status: string;
  zipcode:string;
  accountNumber:string;
  balance:number;
  longDistance:number;
  longDistanceBillType:string;
  international:number;
  local:number;
  dropped:number;
  paymentMethod:string;
  localBillType: string;
  churn: string;
  churnRisk: number;
  deviceOwned: string;
  mostDominantTone: string;
}
